worldRestaurants.controller('countryController', function($scope) {

//$scope.printzz = function() { console.log("lalalalala");}
$scope.selectedCountries = []
$scope.country = [
    { name: 'Afghanistan', region: 'Asia', color: '#FFF'},
    { name: 'Albania', region: 'Europe', color: '#FFF'},
    { name: 'Algeria', region: 'Africa', color: '#FFF'},
    { name: 'American Samoa', region: 'Australasia', color: '#FFF'},
    { name: 'Andorra', region: 'Europe', color: '#FFF'},
    { name: 'Angola', region: 'Africa', color: '#FFF'},
    { name: 'Anguilla', region: 'Caribbean', color: '#FFF'},
    { name: 'Antigua and Barbuda', region: 'Caribbean', color: '#FFF'},
    { name: 'Argentina', region: 'South America', color: '#FFF'},
    { name: 'Armenia', region: 'Europe', color: '#FFF'},
    { name: 'Aruba', region: 'Caribbean', color: '#FFF'},
    { name: 'Australia', region: 'Australasia', color: '#FFF', number: 8},
    { name: 'Austria', region: 'Europe', color: '#FFF'},
    { name: 'Azerbaijan', region: 'Europe', color: '#FFF'},
    { name: 'Bahamas', region: 'Caribbean', color: '#FFF'},
    { name: 'Bahrain', region: 'Middle East', color: '#FFF'},
    { name: 'Bangladesh', region: 'Asia', color: '#FFF'},
    { name: 'Barbados', region: 'Caribbean', color: '#FFF'},
    { name: 'Belarus', region: 'Europe', color: '#FFF'},
    { name: 'Belgium', region: 'Europe', color: '#FFF'},
    { name: 'Belize', region: 'North America', color: '#FFF'},
    { name: 'Benin', region: 'Africa', color: '#FFF'},
    { name: 'Bermuda', region: 'Caribbean', color: '#FFF'},
    { name: 'Bhutan', region: 'Asia', color: '#FFF'},
    { name: 'Bolivia', region: 'South America', color: '#FFF'},
    { name: 'Bosnia-Herzegovina', region: 'Europe', color: '#FFF'},
    { name: 'Botswana', region: 'Africa', color: '#FFF'},
    { name: 'Bouvet Island', region: 'Africa', color: '#FFF'},
    { name: 'Brazil', region: 'South America', color: '#FFF'},
    { name: 'Brunei', region: 'Asia', color: '#FFF'},
    { name: 'Bulgaria', region: 'Europe', color: '#FFF'},
    { name: 'Burkina Faso', region: 'Africa', color: '#FFF'},
    { name: 'Burundi', region: 'Africa', color: '#FFF'},
    { name: 'Cambodia', region: 'Asia', color: '#FFF'},
    { name: 'Cameroon', region: 'Africa', color: '#FFF'},
    { name: 'Canada', region: 'North America', color: '#FFF'},
    { name: 'Cape Verde', region: 'Africa', color: '#FFF'},
    { name: 'Cayman Islands', region: 'Caribbean', color: '#FFF'},
    { name: 'Central African Republic', region: 'Africa', color: '#FFF'},
    { name: 'Chad', region: 'Africa', color: '#FFF'},
    { name: 'Chile', region: 'South America', color: '#FFF'},
    { name: 'China', region: 'Asia', color: '#FFF'},
    { name: 'Christmas Island', region: 'Australasia', color: '#FFF'},
    { name: 'Cocos (Keeling) Islands', region: 'Australasia', color: '#FFF'},
    { name: 'Colombia', region: 'South America', color: '#FFF'},
    { name: 'Comoros', region: 'Africa', color: '#FFF'},
    { name: 'Congo, Democratic Republic of the (Zaire)', region: 'Africa', color: '#FFF'},
    { name: 'Congo, Republic of', region: 'Africa', color: '#FFF'},
    { name: 'Cook Islands', region: 'Australasia', color: '#FFF'},
    { name: 'Costa Rica', region: 'North America', color: '#FFF'},
    { name: 'Croatia', region: 'Europe', color: '#FFF'},
    { name: 'Cuba', region: 'Caribbean', color: '#FFF'},
    { name: 'Cyprus', region: 'Europe', color: '#FFF'},
    { name: 'Czech Republic', region: 'Europe', color: '#FFF'},
    { name: 'Denmark', region: 'Europe', color: '#FFF'},
    { name: 'Djibouti', region: 'Africa', color: '#FFF'},
    { name: 'Dominica', region: 'Caribbean', color: '#FFF'},
    { name: 'Dominican Republic', region: 'Caribbean', color: '#FFF'},
    { name: 'Ecuador', region: 'South America', color: '#FFF'},
    { name: 'Egypt', region: 'Africa', color: '#FFF'},
    { name: 'El Salvador', region: 'North America', color: '#FFF'},
    { name: 'Equatorial Guinea', region: 'Africa', color: '#FFF'},
    { name: 'Eritrea', region: 'Africa', color: '#FFF'},
    { name: 'Estonia', region: 'Europe', color: '#FFF'},
    { name: 'Ethiopia', region: 'Africa', color: '#FFF'},
    { name: 'Falkland Islands', region: 'South America', color: '#FFF'},
    { name: 'Faroe Islands', region: 'Europe', color: '#FFF'},
    { name: 'Fiji', region: 'Australasia', color: '#FFF'},
    { name: 'Finland', region: 'Europe', color: '#FFF'},
    { name: 'France', region: 'Europe', color: '#FFF'},
    { name: 'French Guiana', region: 'South America', color: '#FFF'},
    { name: 'Gabon', region: 'Africa', color: '#FFF'},
    { name: 'Gambia', region: 'Africa', color: '#FFF'},
    { name: 'Georgia', region: 'Europe', color: '#FFF'},
    { name: 'Germany', region: 'Europe', color: '#FFF'},
    { name: 'Ghana', region: 'Africa', color: '#FFF'},
    { name: 'Gibraltar', region: 'Europe', color: '#FFF'},
    { name: 'Greece', region: 'Europe', color: '#FFF'},
    { name: 'Greenland', region: 'Europe', color: '#FFF'},
    { name: 'Grenada', region: 'Caribbean', color: '#FFF'},
    { name: 'Guadeloupe (French)', region: 'Caribbean', color: '#FFF'},
    { name: 'Guam (USA)', region: 'Australasia', color: '#FFF'},
    { name: 'Guatemala', region: 'North America', color: '#FFF'},
    { name: 'Guinea', region: 'Africa', color: '#FFF'},
    { name: 'Guinea Bissau', region: 'Africa', color: '#FFF'},
    { name: 'Guyana', region: 'South America', color: '#FFF'},
    { name: 'Haiti', region: 'Caribbean', color: '#FFF'},
    { name: 'Holy See', region: 'Europe', color: '#FFF'},
    { name: 'Honduras', region: 'North America', color: '#FFF'},
    { name: 'Hong Kong', region: 'Asia', color: '#FFF'},
    { name: 'Hungary', region: 'Europe', color: '#FFF'},
    { name: 'Iceland', region: 'Europe', color: '#FFF'},
    { name: 'India', region: 'Asia', color: '#FFF'},
    { name: 'Indonesia', region: 'Asia', color: '#FFF'},
    { name: 'Iran', region: 'Middle East', color: '#FFF'},
    { name: 'Iraq', region: 'Middle East', color: '#FFF'},
    { name: 'Ireland', region: 'Europe', color: '#FFF'},
    { name: 'Israel', region: 'Middle East', color: '#FFF'},
    { name: 'Italy', region: 'Europe', color: '#FFF'},
    { name: 'Ivory Coast (Cote D`Ivoire)', region: 'Africa', color: '#FFF'},
    { name: 'Jamaica', region: 'Caribbean', color: '#FFF'},
    { name: 'Japan', region: 'Asia', color: '#FFF'},
    { name: 'Jordan', region: 'Middle East', color: '#FFF'},
    { name: 'Kazakhstan', region: 'Asia', color: '#FFF'},
    { name: 'Kenya', region: 'Africa', color: '#FFF'},
    { name: 'Kiribati', region: 'Australasia', color: '#FFF'},
    { name: 'Kuwait', region: 'Middle East', color: '#FFF'},
    { name: 'Kyrgyzstan', region: 'Asia', color: '#FFF'},
    { name: 'Laos', region: 'Asia', color: '#FFF'},
    { name: 'Latvia', region: 'Europe', color: '#FFF'},
    { name: 'Lebanon', region: 'Middle East', color: '#FFF'},
    { name: 'Lesotho', region: 'Africa', color: '#FFF'},
    { name: 'Liberia', region: 'Africa', color: '#FFF'},
    { name: 'Libya', region: 'Africa', color: '#FFF'},
    { name: 'Liechtenstein', region: 'Europe', color: '#FFF'},
    { name: 'Lithuania', region: 'Europe', color: '#FFF'},
    { name: 'Luxembourg', region: 'Europe', color: '#FFF'},
    { name: 'Macau', region: 'Asia', color: '#FFF'},
    { name: 'Macedonia', region: 'Europe', color: '#FFF'},
    { name: 'Madagascar', region: 'Africa', color: '#FFF'},
    { name: 'Malawi', region: 'Africa', color: '#FFF'},
    { name: 'Malaysia', region: 'Asia', color: '#FFF'},
    { name: 'Maldives', region: 'Asia', color: '#FFF'},
    { name: 'Mali', region: 'Africa', color: '#FFF'},
    { name: 'Malta', region: 'Europe', color: '#FFF'},
    { name: 'Marshall Islands', region: 'Australasia', color: '#FFF'},
    { name: 'Martinique (French)', region: 'Caribbean', color: '#FFF'},
    { name: 'Mauritania', region: 'Africa', color: '#FFF'},
    { name: 'Mauritius', region: 'Africa', color: '#FFF'},
    { name: 'Mayotte', region: 'Africa', color: '#FFF'},
    { name: 'Mexico', region: 'North America', color: '#FFF'},
    { name: 'Micronesia', region: 'Australasia', color: '#FFF'},
    { name: 'Moldova', region: 'Europe', color: '#FFF'},
    { name: 'Monaco', region: 'Europe', color: '#FFF'},
    { name: 'Mongolia', region: 'Asia', color: '#FFF'},
    { name: 'Montenegro', region: 'Europe', color: '#FFF'},
    { name: 'Montserrat', region: 'Caribbean', color: '#FFF'},
    { name: 'Morocco', region: 'Africa', color: '#FFF'},
    { name: 'Mozambique', region: 'Africa', color: '#FFF'},
    { name: 'Myanmar', region: 'Asia', color: '#FFF'},
    { name: 'Namibia', region: 'Africa', color: '#FFF'},
    { name: 'Nauru', region: 'Australasia', color: '#FFF'},
    { name: 'Nepal', region: 'Asia', color: '#FFF'},
    { name: 'Netherlands', region: 'Europe', color: '#FFF'},
    { name: 'Netherlands Antilles', region: 'Caribbean', color: '#FFF'},
    { name: 'New Caledonia (French)', region: 'Australasia', color: '#FFF'},
    { name: 'New Zealand', region: 'Australasia', color: '#FFF'},
    { name: 'Nicaragua', region: 'North America', color: '#FFF'},
    { name: 'Niger', region: 'Africa', color: '#FFF'},
    { name: 'Nigeria', region: 'Africa', color: '#FFF'},
    { name: 'Niue', region: 'Australasia', color: '#FFF'},
    { name: 'Norfolk Island', region: 'Australasia', color: '#FFF'},
    { name: 'North Korea', region: 'Asia', color: '#FFF'},
    { name: 'Northern Mariana Islands', region: 'Asia', color: '#FFF'},
    { name: 'Norway', region: 'Europe', color: '#FFF'},
    { name: 'Oman', region: 'Middle East', color: '#FFF'},
    { name: 'Pakistan', region: 'Asia', color: '#FFF'},
    { name: 'Palau', region: 'Australasia', color: '#FFF'},
    { name: 'Panama', region: 'North America', color: '#FFF'},
    { name: 'Papua New Guinea', region: 'Australasia', color: '#FFF'},
    { name: 'Paraguay', region: 'South America', color: '#FFF'},
    { name: 'Peru', region:'South America', color: '#FFF'},
    { name: 'Philippines', region: 'Asia', color: '#FFF'},
    { name: 'Pitcairn Island', region: 'Australasia', color: '#FFF'},
    { name: 'Poland', region: 'Europe', color: '#FFF'},
    { name: 'Polynesia (French)', region: 'Australasia', color: '#FFF'},
    { name: 'Portugal', region: 'Europe', color: '#FFF'},
    { name: 'Puerto Rico', region: 'Caribbean', color: '#FFF'},
    { name: 'Qatar', region: 'Middle East', color: '#FFF'},
    { name: 'Reunion', region: 'Africa', color: '#FFF'},
    { name: 'Romania', region: 'Europe', color: '#FFF'},
    { name: 'Russia', region: 'Europe', color: '#FFF'},
    { name: 'Rwanda', region: 'Africa', color: '#FFF'},
    { name: 'Saint Helena', region: 'Africa', color: '#FFF'},
    { name: 'Saint Kitts and Nevis', region: 'Caribbean', color: '#FFF'},
    { name: 'Saint Lucia', region: 'Caribbean', color: '#FFF'},
    { name: 'Saint Pierre and Miquelon', region: 'North America', color: '#FFF'},
    { name: 'Saint Vincent and Grenadines', region: 'Caribbean', color: '#FFF'},
    { name: 'Samoa', region: 'Australasia', color: '#FFF'},
    { name: 'San Marino', region: 'Europe', color: '#FFF'},
    { name: 'Sao Tome and Principe', region: 'Africa', color: '#FFF'},
    { name: 'Saudi Arabia', region: 'Middle East', color: '#FFF'},
    { name: 'Senegal', region: 'Africa', color: '#FFF'},
    { name: 'Serbia', region: 'Europe', color: '#FFF'},
    { name: 'Seychelles', region: 'Africa', color: '#FFF'},
    { name: 'Sierra Leone', region: 'Africa', color: '#FFF'},
    { name: 'Singapore', region: 'Asia', color: '#FFF'},
    { name: 'Slovakia', region: 'Europe', color: '#FFF'},
    { name: 'Slovenia', region: 'Europe', color: '#FFF'},
    { name: 'Solomon Islands', region: 'Australasia', color: '#FFF'},
    { name: 'Somalia', region: 'Africa', color: '#FFF'},
    { name: 'South Africa', region: 'Africa', color: '#FFF'},
    { name: 'South Georgia and South Sandwich Islands', region: 'South America', color: '#FFF'},
    { name: 'South Korea', region: 'Asia', color: '#FFF'},
    { name: 'South Sudan', region: 'Africa', color: '#FFF'},
    { name: 'Spain', region: 'Europe', color: '#FFF'},
    { name: 'Sri Lanka', region: 'Asia', color: '#FFF'},
    { name: 'Sudan', region: 'Africa', color: '#FFF'},
    { name: 'Suriname', region: 'South America', color: '#FFF'},
    { name: 'Svalbard and Jan Mayen Islands', region: 'Europe', color: '#FFF'},
    { name: 'Swaziland', region: 'Africa', color: '#FFF'},
    { name: 'Sweden', region: 'Europe', color: '#FFF'},
    { name: 'Switzerland', region: 'Europe', color: '#FFF'},
    { name: 'Syria', region: 'Middle East', color: '#FFF'},
    { name: 'Taiwan', region: 'Asia', color: '#FFF'},
    { name: 'Tajikistan', region: 'Asia', color: '#FFF'},
    { name: 'Tanzania', region: 'Africa', color: '#FFF'},
    { name: 'Thailand', region: 'Asia', color: '#FFF'},
    { name: 'Timor-Leste (East Timor)', region: 'Australasia', color: '#FFF'},
    { name: 'Togo', region: 'Africa', color: '#FFF'},
    { name: 'Tokelau', region: 'Australasia', color: '#FFF'},
    { name: 'Tonga', region: 'Australasia', color: '#FFF'},
    { name: 'Trinidad and Tobago', region: 'Caribbean', color: '#FFF'},
    { name: 'Tunisia', region: 'Africa', color: '#FFF'},
    { name: 'Turkey', region: 'Middle East', color: '#FFF'},
    { name: 'Turkmenistan', region: 'Asia', color: '#FFF'},
    { name: 'Turks and Caicos Islands', region: 'Caribbean', color: '#FFF'},
    { name: 'Tuvalu', region: 'Australasia', color: '#FFF'},
    { name: 'Uganda', region: 'Africa', color: '#FFF'},
    { name: 'Ukraine', region: 'Europe', color: '#FFF'},
    { name: 'United Arab Emirates', region: 'Middle East', color: '#FFF'},
    { name: 'United Kingdom', region: 'Europe', color: '#FFF'},
    { name: 'United States', region: 'North America', color: '#FFF'},
    { name: 'Uruguay', region: 'South America', color: '#FFF'},
    { name: 'Uzbekistan', region: 'Asia', color: '#FFF'},
    { name: 'Vanuatu', region: 'Australasia', color: '#FFF'},
    { name: 'Venezuela', region: 'South America', color: '#FFF'},
    { name: 'Vietnam', region: 'Asia', color: '#FFF'},
    { name: 'Virgin Islands', region: 'Caribbean', color: '#FFF'},
    { name: 'Wallis and Futuna Islands', region: 'Australasia', color: '#FFF'},
    { name: 'Yemen', region: 'Middle East', color: '#FFF'},
    { name: 'Zambia', region: 'Africa', color: '#FFF'}
];
};);